# See https://docs.docker.com/build/ci/github-actions/

# https://github.com/docker/build-push-action

name: docker container

on: 
  push:
    branches:
      - main
      - container

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ls
        run: pwd; ls -al

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: landreman
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: landreman/machine_learning

